before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: cOStNt9OF88XRj5UNgjQ5LZQRhSixb95jbuOzUOspeazQ4SxwflAexvsRqHNd1+4LIp3FSgCRiROKNSXZut6w1GQi7cXtjFhwYJw3Bsxx89WewjgtcVUO4N4ZztTOVyPlQDxfXYDUh59Qy7MThwU2v1TNMGXaPd35xcNH90SLa5Kcv8qPAi13w+Uyjl+j2xihQwyAGUpFjhJY0MahEw5Gn0fV0wWXwmIx066vioj79X6NzuQolhMJ/3Ez8c3sf+gOoV6lwMLuuyN4pTf243tZgsPmt3yli5buBzbEvyc3+pcfuO0NqF3wznDtiWDquayzASB8HdVstQKHBKYZafhUg2ZBHFvfAPWRJUYcEBPOk9D89LKk34a4bbJSyx5yNJTPMgC6tyGSCdOb0z5iHPLT1vBxyFbmyhhHxUVs6v0QAijQ+IJSu/QnJ/WxMoanW9AVu+Q2CViGNbG1LAnuzR4pfFTtbg9pKqz62amhpP94Xf8OPdSEIjI0zK9IdH+ykUDuvESiAmrqo8VbswHpZ8cwFfUWmPvizzLTV9IcdcjEUVwonuuINOUqSzjWg+9ROevkj/btGhHyjc5i/dKcQo7MqlYsTgnJlJWojiP8t6oluc9fyyPvrLLLLB01MvDeNlR90i5Ok3XXPrfbJQWf+Vx+i2x58kd2kHhtWfhgLuWalw= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
